Module1 task2
htmlacademy-yii/792223-task-force-1 pull request #2
Opened 2019-10-11 19:32 UTC by k0ality

Камень судьбы, но без assert

2019-10-12 04:45 UTC, caseycs requested changes
Единственный критичный момент - это действие с отправкой сообщения. Все остальное - тонкости и вкусовщина, т.к. ты просила въедливое код-ревью.

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +    public const ACTION_COMPLETE = 'завершить';
Есть еще действие "отправить сообщение"

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +    public const STATUS_CANCELLED = 'отменено/провалено';
Я бы сказал это два разных статуса - отменено заказчиком и отменено исполнителем (т.е. провалено)

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +    public function __construct($user_id, $expires_at)
Вообще по тз свойств больше, но пока это не критично.

Дату лучше передавать и хранить внтури в виде объекта DateTime, это также не критично пока.

Также неплохо бы использовать type-hinting для аргументов, но это в идеале.

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +        return null;
Выходит метод возвращает когда-то строку, а когда-то - null. Ситуация когда запрашивается роль для не-автора и не-исполнителя - на мой взгляд вырожденная, я стараюсь в таких случаях кидать исключения. Но тут тонкий момент, не критично, просто поделился.

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +            return null;
А почему не пустой массив? Опять же - два типа возвращаемого значения мне кажется не лучшей идеей.

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +        return null;
Я бы предложил кидать исключение

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +        return $statusName;
Ты же мысль с исключением

2019-10-12 04:45 UTC, caseycs commented on pages/browse.html
> +    <link rel="stylesheet" href="../css/normalize.css">
Лучшуюе пути к ресурсам указывать относительно корня проекта, чтобы это работало для урлов любой вложенности

2019-10-12 04:45 UTC, caseycs commented on app/Models/Task.php
> +    public const ROLE_OWNER = 'заказчик';
Значения констант я бы написал по-английски, ибо они скорее всего будут храниться в БД, т.е. чтобы не было даже соблазна брать текст из базы в шаблоне.

2019-10-12 11:16 UTC, k0ality commented on app/Models/Task.php
> +    public const ACTION_COMPLETE = 'завершить';
да, чёт просмотрела. добавила

2019-10-12 11:17 UTC, k0ality commented on app/Models/Task.php
> +    public const STATUS_CANCELLED = 'отменено/провалено';
Читала в ТЗ про сортировку и сбило с толку то что написано в Мои Задания. "Отменённые – все задания со статусом «Отменено» и «Провалено», где пользователь является заказчиком или исполнителем".
Исправила.

2019-10-12 11:24 UTC, k0ality commented on app/Models/Task.php
> +    public function __construct($user_id, $expires_at)
Добавила те свойства которые ещё предполагаю добавить в дальнейшем. Но может что-то поменяется, и в любом случае пока их нет пусть будут закомментированы.
В методах добавила декларации пока что со стандартными типами.

2019-10-12 11:26 UTC, k0ality commented on app/Models/Task.php
> +        return null;
Соглашусь что меня тоже это смущает. Но пока не знаю как переделать. Оставлю комментарий чтоб подумать на следующих разделах. Вроде работа с исключениями ещё впереди :)

2019-10-12 11:27 UTC, k0ality commented on app/Models/Task.php
> +            return null;
Тут всё исправила на пустой массив.

2019-10-12 11:28 UTC, k0ality commented on app/Models/Task.php
> +        return $statusName;
Не, тут вроде получается что статус может не поменяться. Я тогда возвращаю текущий. Например для "отправить сообщение" и для "отозваться".
Или я неправильно поняла?

2019-10-12 11:28 UTC, k0ality commented on pages/browse.html
> +    <link rel="stylesheet" href="../css/normalize.css">
Это я пока просто перекинула в отдельную папку, чтоб не мешало. Потом же по идее на php шаблонизируем?

2019-10-12 11:29 UTC, k0ality commented on app/Models/Task.php
> +    public const ROLE_OWNER = 'заказчик';
Сделала на англ и скинула всё в интерфейсы. Чуть сищу чтоб было.

2019-10-12 14:52 UTC, caseycs requested changes

2019-10-12 14:52 UTC, caseycs commented on app/TaskActions.php
> +    const ACTION_APPLY = 'apply';
Если уж предираться - то стоит указывать область видимости, т.е. `public const`

2019-10-12 14:52 UTC, caseycs commented on pages/browse.html
> +    <link rel="stylesheet" href="../css/normalize.css">
Шаблонизируем - да, но в шаблонах тоже путь лучше стоит указывать начиная со слеша, чтобы не зависеть от урла страницы.

2019-10-12 18:18 UTC, k0ality commented on app/TaskActions.php
> +    const ACTION_APPLY = 'apply';
fixed

2019-10-13 09:26 UTC, k0ality commented on pages/browse.html
> +    <link rel="stylesheet" href="../css/normalize.css">
Давай я исправлю в следующем ПР. Получилось так что я тут уже подключила автолоадер, а это только следующее задание. И мне нечего будет кинуть га ПР)
А вообще шаблонизация это вроде аж 4 раздел.

2019-10-13 18:59 UTC, caseycs commented on pages/browse.html
> +    <link rel="stylesheet" href="../css/normalize.css">
Ок, договорились

2019-10-13 19:02 UTC, caseycs commented on app/Models/Task.php
> +        return $statusName;
Тут тонкий момент. Смотри, у нас нигде нет проверки "от дурака", что входящий аргумент будет валидным статусом. Я стараюсь писать "дуракоустойчиво", т.е. чтобы программа в нештатной ситуации ни в коем случае не делала вид что все хорошо. Т.е. я стараюсь проверять все переданные аргументы к примеру. В данном случае - я бы обработал действие отправки сообщения и вернул бы на него текущий статус. А в конце бросил бы исключение - т.е. если экшн неизвестен.

Но это уже детали, тонкости и т.д

2019-10-13 19:09 UTC, caseycs approved these changes

2019-10-13 19:09 UTC, caseycs commented on app/Models/Task.php
> +    public function __construct(int $user_id, string $expired_at)
Идея была в том, чтобы передавать объект datetime, вместо строки которая потом будет преобразована в datetime. Это позводит написать В декларации `\DateTime $expired_at`

2019-10-13 19:09 UTC, caseycs commented on app/Models/Task.php
> +    public function __construct(int $user_id, string $expired_at)
Также это снимает кучу вопросов: а что это за строка, а как она используется, а что будет если там невалидная дата/время и т.д.

А вообще в общем случае в ООП подходе всегда лучше передавать объект, чем скаляр.

2019-10-13 19:09 UTC, merged