add database schema
htmlacademy-yii/792223-task-force-1 pull request #4
Opened 2019-10-19 18:42 UTC by k0ality

2019-10-20 06:10 UTC, caseycs requested changes

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `zip-code` VARCHAR(45) NULL,
Лучше не использовать тире, по двум причинам
1) чтобы именование было в одном стиле - сейчас где-то тире, а где-то подчеркивания
2) при работе с orm обращаться к полю с тире в названии сложнее, ибо php не поддерживает тире в названии свойств классов

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  UNIQUE INDEX `city_name_UNIQUE` (`city_name` ASC))
С таким индексом нельзя будет создать два адреса в одном городе

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `email` VARCHAR(320) NOT NULL,
Могут быть в системе два пользователя с одним email?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `last_active_at` DATETIME NULL,
А может быть пользователь без этой даты? Ведь он должен был зарегистрироваться, а значит в момент регистрации он был активен.

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +ENGINE = InnoDB;
Я стараюсь скоре делать поля not null, кроме случаев, когда например у задачи может не быть исполнителя (например сразу после создания). Чем меньше вариативности - чем проще как правило, чтобы потом не разбираться - это поле пустое или null. Опять же - такой подход поможет при использовании строгой типизации.

Т.е. я предлагаю updated_at тоже везде делать not null

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `is_rejected` TINYINT NULL,
Хм, а зачем этот флаг - правильно ли я понимаю, что он про то, что исполнитель отозвал свою заявку?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `is_rejected` TINYINT NULL,
В этом случае я бы назвал понятнее, чтобы было проще понять новому в проекте человеку. 

Также напрашивается статус вместо одного флага - ведь заявка может быть просто создана, принята и отозвана.

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`task_statuses` (
Не вижу я особого смысла в таблице статусов, но - это и не плохо. Посмотрим насколько удобно будет с ней работать.

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `is_completed` TINYINT NOT NULL,
А зачем этот флаг?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `fav_id` INT NOT NULL,
А откуда этот id?  К какой сущности он относится?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `author_id` INT NOT NULL,
А на что ссылается этот id?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `model_type` VARCHAR(45) NULL,
Что может быть в этом поле?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `task_id` INT NOT NULL,
А если в рамках одно задания один исполнитель был сперва выбран, с ним был диалог, потом он отказался, потом был выбран другой. Выходит другой увидит переписку с первым?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `status_id` INT NOT NULL,
Я бы сделал тут просто enum со статусом, см. Выше

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`user_settings` (
Вроде как в ТЗ этого не было, а зачем отдельная таблица? Это же только усложняет все, каждый раз надо думать - что в какой таблице хранится.

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`notifications` (
Вроде бы в тз тоже не было, но это не критично

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `author_id` INT NOT NULL,
А кто получатель сообщения?

2019-10-20 06:10 UTC, caseycs commented on schema.sql
> +  `failed_tasks` INT NULL DEFAULT 0,
А почему счетчики могут быть null? Выше тоже про это писал.

2019-10-20 18:43 UTC, k0ality commented on schema.sql
> +  `is_rejected` TINYINT NULL,
Это про то что заказчик может отклонить заявку исполнителя.
ТЗ: "Клик по кнопке «Отказать» помечает отклик как отклонённый и больше не показывает кнопки доступных действий для этого отклика."
Мне кажется легче показывать все кроме отклонённых, чем в статусе new && accepted7

2019-10-20 18:45 UTC, k0ality commented on schema.sql
> +  `is_completed` TINYINT NOT NULL,
Завершение задания
Выполняется после заполнения формы завершения задания на странице задания.  Последовательность действий:
ТЗ: "Убедиться, что выбрано одно из значений в radio button «задание выполнено?»
(...)
Сохранить новый отклик, в котором будет статус выполненности задания (да или нет), текст комментария (при наличии) и значение оценки (если выбрано)"

2019-10-20 18:46 UTC, k0ality commented on schema.sql
> +  `fav_id` INT NOT NULL,
Предполагалось как просто индекс для favourites, но я уже убрала полиморфические связи.

2019-10-20 18:48 UTC, k0ality commented on schema.sql
> +  `model_type` VARCHAR(45) NULL,
было бы task||user_profile, но вижу что идея была плохая

2019-10-20 18:50 UTC, k0ality commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`notifications` (
Есть. Пункт "Настройки аккаунта" + "Настройки сайта".
Можно добавить просто в users конечно. И добавить везде true по умолчанию.
Просто думалось что модель юзера сильно разрослась) Или это я просто не видела больших :D

2019-10-20 18:52 UTC, k0ality commented on schema.sql
> +  UNIQUE INDEX `city_name_UNIQUE` (`city_name` ASC))
Я с адресами как-то сильно запуталась. И по ТЗ мне показалось что таки список городов фиксирован жёстко и добавить новый адрес нельзя. Но пока что уберу. Если что исправлю в задании где будет нормально описано какой функционал предполагается.

2019-10-20 18:58 UTC, k0ality commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`user_settings` (
Есть. Пункт "Настройки аккаунта" + "Настройки сайта".
Можно добавить просто в users конечно. И добавить везде true по умолчанию.
Просто думалось что модель юзера сильно разрослась) Или это я просто не видела больших :D

2019-10-20 19:06 UTC, k0ality commented on schema.sql
> +  `failed_tasks` INT NULL DEFAULT 0,
fixed, заблуждалась что default не даст сделать null

2019-10-21 11:35 UTC, k0ality commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`task_statuses` (
Посмотрела на это со стороны что данные будут по сути статическими и хоть изменения и вероятны, они будут случатся крайне редко. Это значит что придётся прописать данные в сиде который должен быть на всех окружениях, а потом ещё делать джойны часто. Кроме того, если данные необходимо это изменять, то пусть это будет вместе с изменениями кода, который данные использует.
Убрала эту таблицу, выйду за рамки привычек.

Остался вопрос - для SQL не важно будет на этапе, скажем, миллиона записей, что колонка по которой часто идёт поиск enum а не int?

2019-10-21 12:31 UTC, k0ality commented on schema.sql
> +  `task_id` INT NOT NULL,
Поменяла структуру чатов. Теперь у чата есть task_id, task_owner_id, task_agent_id и этот сет должен быть уникальными.
Так получится что 1 Task to Many Chats при этом owner может открыть n чатов (с agent который отказался, и с agent который актуален в данный момент), а каждый агент только один.

Но всё ещё сомневаюсь в реализации...

2019-10-21 12:39 UTC, k0ality commented on schema.sql
> +  `author_id` INT NOT NULL,
Т.к. чат one-on-one то я думаю можно обойтись без получателя? Показывать всё что есть по chat_id.

2019-10-21 14:09 UTC, caseycs commented on schema.sql
> +  UNIQUE INDEX `city_name_UNIQUE` (`city_name` ASC))
Даже если список жесткий - такой индекс не даст создать две строчки в таблице с одним и тем же городом. Это прямо важно понимать, если не очень ложиться в голове - пиши, не стесняйся.

2019-10-21 14:11 UTC, caseycs commented on schema.sql
> +  `is_completed` TINYINT NOT NULL,
Понял, принято!

2019-10-21 14:12 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`user_settings` (
Да, ты видимо не видела больших)
У тебя верный посыл был - разнести по нескольким таблицам, особенно когда частота обновления данных отличается - это актуально для производительности. Но в учебном проекте предлагаю раньше времени не усложнять.

2019-10-21 14:16 UTC, caseycs commented on schema.sql
> +  INDEX `fk_chats_tasks1_idx` (`task_id` ASC),
Этот индекс избыточный т.к. есть уже `uidx_chat_task_authors`

2019-10-21 14:17 UTC, caseycs commented on schema.sql
> +  `author_id` INT NOT NULL,
Так-то можно, т.е. по логике если не автор - то получатель. Думаю в рамках нашего ТЗ этого хватит,  не будет хватать - добавим.

2019-10-21 14:18 UTC, caseycs commented on schema.sql
> +  `task_id` INT NOT NULL,
Нормальная реализация на первый взгляд, как по мне. Начнем писать код и во что-то упремся - поправим.

2019-10-21 14:28 UTC, caseycs commented on schema.sql
> +  `is_rejected` TINYINT NULL,
Да, все верно ты пишешь. Но смотри, выходит что заявка может быть в нескольких состояниях, а флагом ты отображаешь лишь два из них. Я к тому, что вообще - раз уж хранить данные о статусе отклика - то полные. 

Но в принципе в рамках ТЗ - твоего решения должно быть достаточно.

2019-10-21 14:29 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`task_statuses` (
Внутри enum на самом хранит int (плюс справочник число-текстовое значение один раз на всю таблицу), т.е. разницы в скорости выборки никакой.

2019-10-21 14:31 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`task_statuses` (
Тут даже не в джойнах дело, а в том, что выводить во view статус текстом из БД - не лучшая идея, наверняка в каждом представлении потребовались бы свои фишки - выделение цветом, и т.д. и тебе пришлось бы на что-то так и так "зашиваться". Лучше - на человекопонятное слово, чем на числовой ID.

2019-10-21 14:31 UTC, caseycs commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `taskforce`.`notifications` (
Ок, принято!

2019-10-21 14:32 UTC, caseycs commented on schema.sql
> +  INDEX `fk_qualifications_users1_idx` (`user_id` ASC),
Также избыточный, есть `uidx_qualification `

2019-10-21 14:33 UTC, caseycs commented on schema.sql
> +  INDEX `fk_user_favorites_users1_idx` (`user_id` ASC),
И тут

2019-10-21 14:34 UTC, merged